service: grib2json

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.region}
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:ListBucket"
         - "s3:HeadObject"
         - "s3:PutObject"
         - "s3:GetObject"
       Resource:
         - "arn:aws:s3:::${self:custom.gribBucket}"
         - "arn:aws:s3:::${self:custom.gribBucket}/*"
  environment:
    REGION: ${self:custom.region}
    GRIB_BUCKET: ${self:custom.gribBucket}
    BIN_FILE_PATH: /var/task/eccodes/dist/bin/grib_dump

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  gribBucket: converted-gribs
  region: eu-west-1
  memorySize: 2048
  timeout: 300
  webpack:
    webpackConfig: 'webpack.config.ts'
    packagerOptions:
      scripts:
        - npm rebuild grpc --target=8.1.0 --target_arch=x64 --target_platform=linux --target_libc=glibc

resources:
  Resources:
    GribBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.gribBucket}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
              AllowedOrigins:
                - "*"

functions:
  converter:
    handler: functions/converter.handler
    events:
      - http:
          path: convert
          method: post
          cors: true
      - http:
          path: convert
          method: get
          cors: true