service: grib2json

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.region}
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:ListBucket"
         - "s3:HeadObject"
         - "s3:PutObject"
         - "s3:GetObject"
       Resource:
         - "arn:aws:s3:::${self:custom.gribBucket}"
         - "arn:aws:s3:::${self:custom.gribBucket}/*"
  environment:
    REGION: ${self:custom.region}
    GRIB_BUCKET: ${self:custom.gribBucket}

plugins:
  - serverless-webpack

custom:
  gribBucket: converted-gribs
  region: eu-west-1
  memorySize: 2048
  timeout: 300
  webpack:
    webpackConfig: 'webpack.config.ts'

resources:
  Resources:
    GribBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.gribBucket}

functions:
  create:
    handler: functions/converter.handler
    events:
      - http:
          path: convert
          method: post
          cors: true
      - http:
          path: convert
          method: get
          cors: true